/* Copyright 2019-2021 NXP
 * 
 * SPDX-License-Identifier: Apache-2.0
 * 
 * 
 */

#ifndef SEMS_LITE_AGENT_VERSION_INFO_H_INCLUDED
#define SEMS_LITE_AGENT_VERSION_INFO_H_INCLUDED

/* clang-format off */
#define SEMS_LITE_AGENT_PROD_NAME          "SEMS_Lite_Agent"
#define SEMS_LITE_AGENT_VER_STRING_NUM     "v02.00.01_20210408"
#define SEMS_LITE_AGENT_PROD_NAME_VER_FULL "SEMS_Lite_Agent_v02.00.01_20210408"
#define SEMS_LITE_AGENT_VER_MAJOR          (2u)
#define SEMS_LITE_AGENT_VER_MINOR          (0u)
#define SEMS_LITE_AGENT_VER_DEV            (1u)

/* v02.00 = 20000u */
#define SEMS_LITE_AGENT_VER_MAJOR_MINOR ( 0 \
    | (SEMS_LITE_AGENT_VER_MAJOR * 10000u)    \
    | (SEMS_LITE_AGENT_VER_MINOR))

/* v02.00.01 = 200000001ULL */
#define SEMS_LITE_AGENT_VER_MAJOR_MINOR_DEV ( 0 \
    | (SEMS_LITE_AGENT_VER_MAJOR * 10000*10000u)    \
    | (SEMS_LITE_AGENT_VER_MINOR * 10000u)    \
    | (SEMS_LITE_AGENT_VER_DEV))

/* clang-format on */

/* Version Information:
 * Generated by:
 *     scripts\version_info.py (v2019.01.17_00)
 * 
 * Do not edit this file. Update:
 *     semslite/version_info.txt instead.
 * 
 * prod_name = "SEMS_Lite_Agent"
 * 
 * prod_desc = "SEMS Lite Agent"
 * 
 * lang_c_prefix = prod_name.upper()
 * 
 * lang_namespace = ""
 * 
 * v_major  = "02"
 * 
 * v_minor  = "00"
 * 
 * v_dev    = "01"
 * 
 * v_meta   = ""
 * 
 * maturity = "B"
 * 
 * #
 * # v00.04.00 : Use channel 0
 * #
 * # v00.03.00 : Use channel 1
 * #
 */

#endif /* SEMS_LITE_AGENT_VERSION_INFO_H_INCLUDED */
